#!/usr/bin/env raku
#
# (Re)write t/fixtures/abi-table.tsv from the ABI table in
# src/notcurses_native_shim.c, or with --check verify that the committed
# fixture still matches it.
#
# The table is the ground truth t/42-abi-guard holds the Raku bindings
# to. A live shim answers it directly; the fixture is what t/42 compares
# against when no shim carrying the table is installed (a toolchain-less
# install of a prebuilt pack that predates it, say), so it must be
# regenerated whenever the table changes — t/42 fails, naming this
# script, when a live shim and the fixture disagree. The table's values
# are the same on every supported 64-bit target except the width of a C
# `long` (see width-long in the shim), which t/42 reads per platform, so
# a fixture generated on any of them serves all of them.
#
# Needs a C compiler ($CC, else `cc`) and the pinned notcurses headers:
# $NOTCURSES_NATIVE_VENDOR_DIR/include, else the source cache
# Build.rakumod fills (<cache>/Notcurses-Native-source/<sha>/include).
# No libnotcurses: the probe compiles only the table.
#
#   raku scripts/abi/regenerate-fixture.raku           # rewrite the fixture
#   raku scripts/abi/regenerate-fixture.raku --check   # exit 1 if stale

my IO::Path $root    = $*PROGRAM.absolute.IO.parent.parent.parent;
my IO::Path $probe   = $root.add('scripts/abi/abi-probe.c');
my IO::Path $fixture = $root.add('t/fixtures/abi-table.tsv');

sub pinned-sha(--> Str) {
    my Str $line = $root.add('NOTCURSES_FORK').lines.first(*.starts-with('sha='))
        // die "NOTCURSES_FORK has no sha= line";
    $line.substr(4).trim
}

sub notcurses-include(Str $sha --> IO::Path) {
    with %*ENV<NOTCURSES_NATIVE_VENDOR_DIR> {
        my IO::Path $inc = .IO.add('include');
        return $inc if $inc.add('notcurses/notcurses.h').f;
        die "NOTCURSES_NATIVE_VENDOR_DIR is set, but $inc has no notcurses/notcurses.h";
    }
    my Str $base = %*ENV<NOTCURSES_NATIVE_CACHE_DIR>
        // %*ENV<XDG_CACHE_HOME>
        // "{%*ENV<HOME> // %*ENV<USERPROFILE> // '.'}/.cache";
    my IO::Path $inc = "$base/Notcurses-Native-source/$sha/include".IO;
    return $inc if $inc.add('notcurses/notcurses.h').f;
    die "The notcurses headers for $sha are not at $inc. Set "
      ~ "NOTCURSES_NATIVE_VENDOR_DIR to a checkout of that commit, or "
      ~ "install the dist once from source so Build.rakumod caches it.";
}

# Build and run the probe; answer its lines. Dies with the compiler's or
# the probe's own complaint.
sub probe-lines(IO::Path $include --> List) {
    my IO::Path $work = $*TMPDIR.add("notcurses-native-abi-{$*PID}-{(^2**31).pick}");
    $work.mkdir;
    LEAVE {
        for $work.dir -> $f { try $f.unlink }
        try $work.rmdir;
    }
    my IO::Path $exe = $work.add($*DISTRO.is-win ?? 'abi-probe.exe' !! 'abi-probe');
    my Str $cc = %*ENV<CC> // 'cc';
    my $built = run $cc, '-O1', "-I{$include.absolute}", '-o', $exe.absolute,
        $probe.absolute, :out, :err;
    my Str $cc-out = $built.out.slurp(:close) ~ $built.err.slurp(:close);
    die "Compiling the ABI probe with '$cc' failed:\n$cc-out"
        unless $built.exitcode == 0 && $exe.f;
    my $ran = run $exe.absolute, :out, :err;
    my Str $out = $ran.out.slurp(:close);
    my Str $err = $ran.err.slurp(:close);
    die "The ABI probe failed (exit {$ran.exitcode}, signal {$ran.signal}):\n$err"
        unless $ran.exitcode == 0 && $ran.signal == 0;
    my @lines = $out.lines;
    die "The ABI probe printed a malformed line: {$_.raku}"
        for @lines.grep({ $_ !~~ /^ <[\w:.\[\]\-]>+ \t '-'? \d+ $/ });
    die "The ABI probe printed nothing" unless @lines;
    @lines.List
}

sub render(Str $sha, @lines --> Str) {
    join '', map { "$_\n" },
        '# Notcurses::Native ABI table: struct sizes, field offsets and widths,',
        '# and constant values, as src/notcurses_native_shim.c computes them from',
        '# the pinned notcurses headers. Generated by',
        '# scripts/abi/regenerate-fixture.raku; do not edit by hand.',
        "# notcurses-sha: $sha",
        |@lines
}

sub MAIN(Bool :$check = False) {
    my Str $sha = pinned-sha();
    my Str $fresh = render($sha, probe-lines(notcurses-include($sha)));
    if $check {
        my Str $committed = $fixture.e ?? $fixture.slurp !! '';
        if $committed.lines eqv $fresh.lines {
            say "t/fixtures/abi-table.tsv is current ({$fresh.lines.grep(!*.starts-with('#')).elems} entries).";
            exit 0;
        }
        my %old = $committed.lines.grep(!*.starts-with('#')).map({ .split("\t", 2) }).flat;
        my %new = $fresh.lines.grep(!*.starts-with('#')).map({ .split("\t", 2) }).flat;
        note "t/fixtures/abi-table.tsv is stale; run scripts/abi/regenerate-fixture.raku.";
        note "  notcurses-sha changed" unless $committed.contains("# notcurses-sha: $sha\n");
        note "  missing: $_ ({%new{$_}})"              for (%new.keys (-) %old.keys).keys.sort;
        note "  obsolete: $_ ({%old{$_}})"             for (%old.keys (-) %new.keys).keys.sort;
        note "  changed: $_ ({%old{$_}} -> {%new{$_}})"
            for (%new.keys (&) %old.keys).keys.grep({ %new{$_} ne %old{$_} }).sort;
        exit 1;
    }
    $fixture.spurt($fresh);
    say "Wrote t/fixtures/abi-table.tsv ({$fresh.lines.grep(!*.starts-with('#')).elems} entries, notcurses $sha).";
}
